[package]
name = "dict"
version = "0.1.0"
authors = ["streicher <shumenda |at| gmx |dot| de>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
flate2 = "1.0.12"
thiserror = "1.0.30"
rassert-rs = "1.0"
memmap2 = "0.5"
advisory-lock = "0.3"
